(() => {
'use strict';
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const text=(e,v)=>{if(e)e.textContent=v};
let xp=Number(localStorage.getItem('cyberComputerXP')||0); const xpEl=$('#xp');
function setXP(v){xp=Math.max(0,Number(v)||0);localStorage.setItem('cyberComputerXP',xp);text(xpEl,xp);text($('#quizXP'),xp+' XP');text($('#buildXP'),xp)}
function addXP(n){setXP(xp+n)} setXP(xp);

/* ===== VOICE ===== */
const voiceStyle=document.createElement('style');voiceStyle.textContent=`.speak-btn{display:inline-flex;align-items:center;gap:7px;margin-top:10px;padding:8px 12px;border:1px solid rgba(35,220,255,.35);border-radius:10px;background:#0b1722;color:#bff7ff;cursor:pointer;font:inherit}.speak-btn:hover{background:#102534;border-color:#28dfff}.speak-btn.speaking{box-shadow:0 0 0 2px rgba(42,220,255,.18);color:#fff}.voice-row{display:flex;justify-content:flex-start;gap:8px;flex-wrap:wrap;margin-top:8px}`;document.head.appendChild(voiceStyle);
let currentSpeech=null;
function speak(value,btn){if(!('speechSynthesis' in window)){alert('المتصفح لا يدعم القراءة الصوتية. استخدم Chrome أو Edge.');return} if(currentSpeech){speechSynthesis.cancel();$$('.speak-btn').forEach(b=>b.classList.remove('speaking'));currentSpeech=null} if(!value)return;const u=new SpeechSynthesisUtterance(value);u.lang='ar-EG';u.rate=.92;u.pitch=1;currentSpeech=u;if(btn)btn.classList.add('speaking');u.onend=u.onerror=()=>{currentSpeech=null;if(btn)btn.classList.remove('speaking')};speechSynthesis.speak(u)}
function addSpeak(el,getText){if(!el||el.querySelector('.speak-btn'))return;const b=document.createElement('button');b.type='button';b.className='speak-btn';b.innerHTML='🔊 استمع';b.addEventListener('click',()=>speak(getText(),b));el.appendChild(b)}
$$('#components article').forEach(a=>addSpeak(a,()=>{const h=a.querySelector('h3'),p=a.querySelector('p');return `${h?.textContent||''}. ${p?.textContent||''}`}));
addSpeak($('#partExplainer'),()=>`${$('#partExplainer h3')?.textContent||''}. ${$('#partExplainer p')?.textContent||''}`);
addSpeak($('#selected-info'),()=>`${$('#infoTitle')?.textContent||''}. ${$('#infoText')?.textContent||''}`);

/* ===== QUIZ: 50 questions, no dependency on 3D ===== */
const questions=[
['ما وظيفة CPU الأساسية؟',['تخزين الملفات','تنفيذ التعليمات والعمليات','عرض الصور فقط','توفير الكهرباء'],1,'المعالج ينفذ التعليمات والعمليات الحسابية والمنطقية.'],
['ما الذي يميز RAM؟',['تخزين دائم','ذاكرة عمل سريعة ومؤقتة','مزود طاقة','بطاقة توسعة'],1,'RAM ذاكرة عمل مؤقتة وتفقد محتواها عند انقطاع الطاقة.'],
['أين يركب المعالج؟',['PCIe','M.2','CPU Socket','DIMM'],2,'المعالج يركب في Socket متوافق مع المنصة.'],
['ما وظيفة Motherboard؟',['التبريد فقط','ربط المكونات وتوفير مسارات الاتصال','التخزين فقط','تشغيل الشاشة فقط'],1,'اللوحة الأم تربط المعالج والذاكرة والتخزين وبطاقات التوسعة والطاقة.'],
['أين يركب GPU المنفصل عادة؟',['DIMM','PCIe x16','SATA','USB-A'],1,'بطاقات الرسوميات المنفصلة تستخدم عادة PCIe x16.'],
['ما M.2؟',['واجهة/شكل لوحدات تخزين وتوسعة','نوع CPU','نوع RAM','نوع مروحة'],0,'M.2 يستخدم كثيرًا مع NVMe SSD.'],
['ما NVMe SSD؟',['تخزين سريع يعمل عادة عبر PCIe','مزود طاقة','مروحة','كابل فيديو'],0,'NVMe بروتوكول تخزين عالي الأداء فوق PCIe.'],
['ما وظيفة PSU؟',['توفير الطاقة المناسبة للمكونات','معالجة الرسوميات','تخزين البيانات','تشغيل BIOS فقط'],0,'PSU يحول الكهرباء ويوفر جهودًا مناسبة للمكونات.'],
['ما موصل الطاقة الرئيسي للوحة؟',['24-Pin ATX','HDMI','RJ45','3.5mm'],0,'24-Pin ATX هو موصل الطاقة الرئيسي للوحة الأم.'],
['ما وظيفة EPS؟',['طاقة المعالج','بيانات SSD','صوت السماعات','إشارة الشاشة'],0,'موصل EPS/CPU Power يمد دائرة المعالج بالطاقة.'],
['ما وظيفة CPU Cooler؟',['خفض حرارة المعالج','زيادة RAM','تخزين الملفات','توفير الإنترنت'],0,'المشتت ينقل الحرارة بعيدًا عن المعالج.'],
['ما BIOS/UEFI؟',['برنامج تهيئة وإقلاع منخفض المستوى','نوع RAM','GPU','برنامج رسم'],0,'UEFI/BIOS يهيئ العتاد ويبدأ الإقلاع.'],
['ما POST؟',['فحص ذاتي عند التشغيل','نوع تخزين','نوع كابل','برنامج تصميم'],0,'POST يفحص المكونات الأساسية عند بدء التشغيل.'],
['أي ذاكرة تفقد محتواها عند انقطاع الطاقة؟',['SSD','RAM','قرص خارجي','ROM'],1,'RAM ذاكرة volatile.'],
['أي مكون يعالج الرسوميات؟',['GPU','PSU','SSD','RAM'],0,'GPU متخصص في الرسوميات والعمليات المتوازية.'],
['ما PCIe؟',['واجهة اتصال عالية السرعة','نظام تشغيل','معجون حراري','نوع شاشة'],0,'PCIe ناقل عالي السرعة لبطاقات التوسعة والتخزين.'],
['لماذا يجب توافق RAM مع اللوحة؟',['كل RAM تعمل دائمًا','جيل DDR والمواصفات يجب أن تتوافق','RAM تحتاج HDMI','RAM تعمل مباشرة من الحائط'],1,'يجب توافق جيل DDR والمنافذ والدعم.'],
['ما الذي يحدد توافق CPU واللوحة؟',['Socket والمنصة والـBIOS','لون اللوحة','الشاشة','الماوس'],0,'التوافق يعتمد على Socket والمنصة ودعم BIOS.'],
['ما Cache؟',['ذاكرة صغيرة وسريعة قرب المعالج','PSU','SSD خارجي','كابل'],0,'Cache تقلل زمن الوصول للبيانات المتكررة.'],
['ما معنى تعدد أنوية CPU؟',['تنفيذ مهام ومسارات أكثر بالتوازي','زيادة التخزين','تبريد الجهاز','زيادة الكهرباء'],0,'الأنوية المتعددة تساعد في تنفيذ مهام متوازية.'],
['كيف تركب CPU؟',['إجباره','محاذاة العلامة وإنزاله برفق','وضعه فوق RAM','تثبيته بالغراء'],1,'يجب محاذاته وعدم إجباره داخل المقبس.'],
['ما فائدة notch في RAM؟',['تحديد اتجاه التركيب','زيادة الإنترنت','التبريد','توصيل الطاقة'],0,'الشق يمنع تركيب الوحدة في الاتجاه الخاطئ.'],
['ماذا تفعل مشابك DIMM؟',['تثبت RAM في مكانها','تشغل الشاشة','تبرد CPU','تغذي GPU'],0,'المشابك تقفل على وحدة الذاكرة.'],
['كيف يركب NVMe؟',['بزاوية ثم يخفض ويثبت','داخل PSU','في CPU Socket','في DIMM'],0,'يدخل طرف M.2 بزاوية ثم يخفض ويثبت.'],
['لماذا المعجون الحراري؟',['تحسين انتقال الحرارة','زيادة SSD','توصيل الكهرباء','تثبيت RAM'],0,'المعجون يحسن انتقال الحرارة بين السطحين.'],
['ما CPU_FAN؟',['موصل مروحة/مضخة المعالج','منفذ SSD','GPU','USB'],0,'يستخدم عادة لتوصيل تبريد المعالج.'],
['ماذا يجب تجنبه مع الموصلات؟',['إجبارها في الاتجاه الخاطئ','فحص الاتجاه','استخدام الكابل المناسب','التأكد من الإحكام'],0,'لا تجبر أي موصل؛ استخدم الاتجاه الصحيح.'],
['لماذا تحتاج GPU قوية إلى PSU مناسب؟',['لأنها تستهلك طاقة كبيرة','لأنها تخزن الملفات','لأنها تستبدل RAM','لأنها تشغل BIOS فقط'],0,'بطاقات الأداء العالي تحتاج قدرة وكابلات مناسبة.'],
['ما وظيفة VRM؟',['تنظيم طاقة المعالج والمكونات','تخزين النظام','عرض الفيديو','توصيل الإنترنت'],0,'VRM ينظم ويحول الطاقة للدوائر الحساسة.'],
['الفرق الأساسي بين SSD وRAM؟',['SSD تخزين دائم نسبيًا وRAM مؤقتة','هما نفس الشيء','RAM دائمة وSSD مؤقت','لا فرق'],0,'SSD يحتفظ بالبيانات دون طاقة، RAM لا.'],
['ما فائدة Dual Channel؟',['زيادة عرض نطاق الذاكرة','زيادة SSD','تبريد CPU','زيادة PSU'],0,'قناتان متوافقتان قد تزيدان عرض نطاق الذاكرة.'],
['HDD يختلف عن SSD في ماذا؟',['HDD ميكانيكي وSSD فلاش','SSD ميكانيكي','HDD فلاش فقط','لا فرق'],0,'HDD يعتمد على أجزاء ميكانيكية بينما SSD يعتمد على فلاش.'],
['ما SATA Data؟',['نقل بيانات وحدات SATA','طاقة CPU','GPU','مروحة'],0,'SATA Data مخصص لنقل البيانات.'],
['ما SATA Power؟',['توفير طاقة لوحدات SATA','نقل فيديو','RAM','BIOS'],0,'SATA Power يمد وحدات SATA بالطاقة.'],
['ما Form Factor؟',['مقاس وتصميم اللوحة/الكيس','سرعة CPU','نوع Windows','سعة RAM'],0,'ATX وMicro-ATX أمثلة على Form Factor.'],
['ما أهمية BIOS للمعالج؟',['قد تحتاج اللوحة BIOS مناسبًا','يزيد الشاشة','يشغل المراوح فقط','لا علاقة'],0,'بعض المعالجات تحتاج إصدار BIOS داعمًا.'],
['ما وظيفة Heatsink؟',['تشتيت الحرارة','تخزين الملفات','توفير الطاقة','توصيل الإنترنت'],0,'المشتت يزيد مساحة تبديد الحرارة.'],
['لماذا تدفق الهواء مهم؟',['لإخراج الحرارة وإدخال هواء أبرد','لزيادة سعة RAM','لتشغيل SSD','لتحديث BIOS'],0,'تدفق الهواء الجيد يحسن درجات الحرارة.'],
['ما Thermal Throttling؟',['خفض الأداء بسبب الحرارة','زيادة سرعة الإنترنت','زيادة التخزين','تعطيل RAM'],0,'المكون قد يخفض تردده لحماية نفسه من الحرارة.'],
['ما وظيفة Case؟',['حماية وتركيب المكونات وتنظيم الهواء','معالجة البيانات','تخزين BIOS','توفير الكهرباء من الحائط'],0,'الكيس يحمل المكونات ويوفر حماية وتدفق هواء.'],
['لماذا تثبيت اللوحة بالمسافات الصحيحة مهم؟',['لمنع تماس غير مرغوب وتنظيم التثبيت','لزيادة RAM','لرفع الإنترنت','لتشغيل GPU'],0,'Standoffs تمنع تماس ظهر اللوحة مع الكيس.'],
['ما وظيفة PCIe slot؟',['تركيب بطاقات توسعة','توصيل السماعات فقط','تخزين BIOS','تغذية الحائط'],0,'PCIe slots تستقبل بطاقات توسعة مثل GPU.'],
['ما المقصود بـ VRAM؟',['ذاكرة تستخدمها GPU','ذاكرة PSU','ذاكرة BIOS فقط','RAM للكيس'],0,'VRAM تخزن بيانات الرسوميات التي تحتاجها GPU.'],
['ما الذي يؤثر في أداء الألعاب؟',['GPU وCPU وRAM والتخزين حسب اللعبة','الكيس فقط','الكابل فقط','لون اللوحة'],0,'الأداء يعتمد على عدة مكونات ونوع اللعبة والإعدادات.'],
['ما وظيفة Power Button Header؟',['إشارة زر تشغيل الكيس للوحة','طاقة GPU','بيانات SSD','مروحة CPU'],0,'يوصل زر التشغيل الموجود في الكيس باللوحة.'],
['ما وظيفة CMOS/UEFI settings؟',['حفظ إعدادات وتهيئة العتاد','تخزين الألعاب','زيادة حجم الشاشة','تغذية GPU'],0,'إعدادات UEFI تضبط سلوك العتاد والإقلاع.'],
['ما المقصود بـ Boot Order؟',['ترتيب الأجهزة التي يحاول النظام الإقلاع منها','ترتيب المراوح','سرعة RAM','حجم GPU'],0,'Boot Order يحدد جهاز الإقلاع الأول ثم التالي.'],
['لماذا نختبر الجهاز بعد التجميع؟',['للتأكد من الإقلاع والتوصيلات والحرارة','لتغيير لون الكيس فقط','لزيادة حجم RAM','لتشغيل HDMI فقط'],0,'اختبار POST والإقلاع والحرارة يكشف أخطاء التجميع.'],
['ما أفضل قاعدة عند تركيب قطع الكمبيوتر؟',['افصل الكهرباء واعمل بهدوء ولا تجبر القطع','اضغط بقوة','استخدم أي كابل','ركب القطع عشوائيًا'],0,'التركيب الصحيح يعتمد على الأمان والمحاذاة والتوافق.'],
['ما المقصود بـ PSU efficiency؟',['مدى كفاءة تحويل الطاقة مع فقد أقل','سعة SSD','سرعة GPU','حجم RAM'],0,'الكفاءة الأعلى تعني فقدًا أقل كحرارة عند نفس الحمل.'],
['ماذا يحدث عند اكتمال تجميع المختبر؟',['يصل التقدم إلى 100% وتحصل على XP','يحذف الموقع','تتوقف الأسئلة','تختفي المكونات'],0,'عند تركيب القطع السبع يكتمل شريط التجميع.']
];
let qi=0,answered=false;const qNumber=$('#qNumber'),questionEl=$('#question'),answersEl=$('#answers'),feedbackEl=$('#feedback'),nextBtn=$('#nextQuestion');
function renderQuestion(){answered=false;const q=questions[qi];text(qNumber,`سؤال ${qi+1} من ${questions.length}`);text(questionEl,q[0]);answersEl.innerHTML='';if(feedbackEl){feedbackEl.textContent='';feedbackEl.className=''}if(nextBtn)nextBtn.disabled=true;addSpeak($('.quiz-card'),()=>`${questionEl.textContent}. ${feedbackEl?.textContent||''}`);q[1].forEach((a,i)=>{const b=document.createElement('button');b.type='button';b.className='answer';b.textContent=`${String.fromCharCode(65+i)}. ${a}`;b.onclick=()=>answerQuestion(i,b);answersEl.appendChild(b)})}
function answerQuestion(i,b){if(answered)return;answered=true;const q=questions[qi],ok=i===q[2];$$('.answer').forEach((x,j)=>{x.disabled=true;if(j===q[2])x.classList.add('correct')});if(!ok)b.classList.add('wrong');if(feedbackEl){feedbackEl.className=ok?'correct':'wrong';feedbackEl.textContent=ok?`✅ إجابة صحيحة! +10 XP — ${q[3]}`:`❌ الإجابة الصحيحة: ${q[1][q[2]]} — ${q[3]}`}if(ok)addXP(10);if(nextBtn)nextBtn.disabled=false}
nextBtn?.addEventListener('click',()=>{if(!answered)return;qi=(qi+1)%questions.length;renderQuestion()});renderQuestion();

/* ===== 3D ENGINE ===== */
const mount=$('#threeScene');let T=null,scene=null,camera=null,renderer=null,board=null;let selectedPart=null,dragging=null,autoRotate=false,wire=false,rotX=-.58,rotY=.55,zoom=11,viewDrag=false,lastX=0,lastY=0;let initialized=false;const objects={},installed=new Set(),targets={};
const names={cpu:'CPU — AMD Ryzen 9 9950X3D',ram:'RAM — DDR5 64GB (2×32GB) 6000MHz',gpu:'GPU — NVIDIA GeForce RTX 5090',ssd:'NVMe SSD — PCIe 5.0 M.2 2TB',cooler:'CPU Cooler — High-End Tower',psu:'PSU — 1200W ATX 3.x',power:'Power Cables — 24-Pin + EPS + GPU'};
const info={cpu:'حاذِ علامة المعالج مع علامة المقبس، أنزل CPU برفق ثم أغلق الذراع.',ram:'حاذِ notch الرامة مع اللسان داخل DIMM واضغط حتى تغلق المشابك.',gpu:'افتح لسان PCIe x16، أدخل البطاقة بشكل مستقيم وثبتها ثم صل طاقة GPU.',ssd:'أدخل NVMe في M.2 بزاوية، اخفضه ثم ثبته.',cooler:'ثبت المشتت بالتساوي وضع المعجون حسب تعليمات الشركة ثم وصل CPU_FAN.',psu:'ثبت PSU واستخدم كابلاته المتوافقة. صل 24-Pin وEPS وطاقة GPU.',power:'صل 24-Pin للوحة وEPS للمعالج وكابل GPU. لا تجبر أي موصل.'};
const status=t=>text($('#sceneStatus'),t);
function loadThree(){if(window.THREE)return Promise.resolve(window.THREE);return new Promise((resolve,reject)=>{const urls=['https://cdnjs.cloudflare.com/ajax/libs/three.js/r147/three.min.js','https://cdn.jsdelivr.net/npm/three@0.147.0/build/three.min.js','https://unpkg.com/three@0.147.0/build/three.min.js'];let i=0;const next=()=>{if(window.THREE)return resolve(window.THREE);if(i>=urls.length)return reject(new Error('Three.js unavailable'));const s=document.createElement('script');s.src=urls[i++];s.onload=()=>window.THREE?resolve(window.THREE):next();s.onerror=next;document.head.appendChild(s)};next()})}
function M(c,r=.5,m=.2){return new T.MeshStandardMaterial({color:c,roughness:r,metalness:m})}let mat={};
function box(p,x,y,z,w,h,d,m){const o=new T.Mesh(new T.BoxGeometry(w,h,d),m);o.position.set(x,y,z);o.castShadow=true;o.receiveShadow=true;p.add(o);return o}
function label(p,s,x,y,z,size=.17){const c=document.createElement('canvas');c.width=512;c.height=96;const g=c.getContext('2d');g.font='bold 40px Arial';g.fillStyle='#c2f7ff';g.textAlign='center';g.textBaseline='middle';g.fillText(s,256,48);const tx=new T.CanvasTexture(c),sp=new T.Sprite(new T.SpriteMaterial({map:tx,transparent:true,depthWrite:false}));sp.scale.set(size*4,size,.01);sp.position.set(x,y,z);p.add(sp)}
function ring(p,r){const o=new T.Mesh(new T.TorusGeometry(r,.035,12,40),new T.MeshBasicMaterial({color:0x00e5ff,transparent:true,opacity:.8}));o.rotation.x=Math.PI/2;o.position.copy(p);scene.add(o)}
function makeBoard(){board=new T.Group();scene.add(board);box(board,0,0,0,9.2,.18,6.9,mat.pcb);box(board,-3.35,.22,-1.8,1,.4,2,mat.dark);box(board,-.75,.22,-1.05,2.2,.16,2,mat.silver);box(board,-.75,.34,-1.05,1.75,.1,1.55,mat.black);label(board,'CPU SOCKET',-.75,.58,-1.05,.16);for(let i=0;i<4;i++){let z=-2.25+i*.82;box(board,2.55,.25,z,.34,.16,.62,mat.black);box(board,2.55,.36,z,.08,.04,.48,mat.gold)}label(board,'DDR5 DIMM',3.1,.58,-.65,.16);for(let i=0;i<3;i++)box(board,-.15,.21,1.55+i*.72,6.1,.12,.2,mat.black);box(board,-.15,.35,1.55,5.75,.08,.42,mat.silver);label(board,'PCIe x16',-2.5,.58,1.55,.16);box(board,1,.35,-.05,2.55,.12,.42,mat.black);box(board,1,.44,-.05,2.2,.03,.07,mat.gold);label(board,'M.2 NVMe',1,.6,-.05,.15);box(board,1.8,.25,2.5,1.6,.4,1.35,mat.silver);label(board,'CHIPSET',1.8,.56,2.5,.14);box(board,3.95,.35,.95,.5,.18,2.25,mat.black);label(board,'24-PIN',3.45,.6,.95,.15);label(board,'MOTHERBOARD',-.2,.43,-2.9,.18)}
function makeTargets(){Object.assign(targets,{cpu:new T.Vector3(-.75,.65,-1.05),ram:new T.Vector3(2.55,.65,-.65),gpu:new T.Vector3(-.15,.68,1.55),ssd:new T.Vector3(1,.58,-.05),cooler:new T.Vector3(-.75,1,-1.05),psu:new T.Vector3(5,.8,2.7),power:new T.Vector3(3.6,.65,.95)});Object.keys(targets).forEach(k=>ring(targets[k],k==='gpu'?2.6:.55))}
function part(type){const g=new T.Group();if(type==='cpu'){box(g,0,.2,0,1.5,.35,1.4,mat.silver);box(g,0,.4,0,1.2,.12,1.08,mat.white);label(g,'RYZEN 9',0,.58,0,.18)}if(type==='ram'){for(let i=0;i<2;i++){let x=-.22+i*.44;box(g,x,.2,0,.27,.55,1.3,mat.black);box(g,x,.49,0,.2,.06,1.12,mat.cyan)}}if(type==='gpu'){box(g,0,.35,0,5.35,.78,1.6,mat.black);box(g,0,.78,0,5,.08,1.38,mat.dark);for(const x of[-1.45,0,1.45]){const f=new T.Mesh(new T.CylinderGeometry(.5,.5,.1,32),mat.dark);f.rotation.x=Math.PI/2;f.position.set(x,.86,0);g.add(f)}label(g,'RTX 5090',0,1.05,0,.22)}if(type==='ssd'){box(g,0,.18,0,2.35,.14,.38,mat.black);box(g,-.35,.29,0,.7,.1,.28,mat.silver);label(g,'NVMe PCIe 5.0',0,.42,0,.14)}if(type==='cooler'){box(g,0,1.25,0,1.7,2,1.35,mat.silver);box(g,0,1.25,.72,1.25,1.3,.12,mat.black);label(g,'TOWER COOLER',0,2.35,.72,.14)}if(type==='psu'){box(g,0,.7,0,2.5,1.5,2.4,mat.black);box(g,0,1.45,0,1.5,.08,1.5,mat.dark);label(g,'1200W PSU',0,1.62,0,.17)}if(type==='power'){for(const[x,z,w]of[[-1.6,-1.2,2.6],[1.4,.5,2.2],[1.7,1.2,1.7]]){const m=new T.Mesh(new T.CylinderGeometry(.07,.07,w,12),mat.black);m.rotation.z=Math.PI/2;m.position.set(x,.35,z);g.add(m)}label(g,'POWER',0,.65,0,.16)}g.userData.partType=type;return g}
function applyCamera(){if(!camera)return;camera.position.set(Math.sin(rotY)*Math.cos(rotX)*zoom,Math.sin(rotX)*zoom+2,Math.cos(rotY)*Math.cos(rotX)*zoom);camera.lookAt(0,0,0)}
function resize(){if(!renderer||!mount)return;const w=Math.max(320,mount.clientWidth||700),h=Math.max(360,mount.clientHeight||620);renderer.setSize(w,h,false);camera.aspect=w/h;camera.updateProjectionMatrix()}
function updateInfo(type){if($('#selectedBox'))$('#selectedBox').innerHTML=`<b>${names[type]}</b><br>${info[type]}`;text($('#infoTitle'),names[type]);text($('#infoText'),info[type]);if($('#partExplainer'))$('#partExplainer').innerHTML=`<h3>💡 ${names[type]}</h3><p>${info[type]}</p>`;addSpeak($('#partExplainer'),()=>`${$('#partExplainer h3')?.textContent||''}. ${$('#partExplainer p')?.textContent||''}`);addSpeak($('#selected-info'),()=>`${$('#infoTitle')?.textContent||''}. ${$('#infoText')?.textContent||''}`)}
function showPart(type){if(!initialized||installed.has(type))return;if(objects[type])scene.remove(objects[type]);const pos={cpu:new T.Vector3(-6,2,-4),ram:new T.Vector3(6,2,-3),gpu:new T.Vector3(6,1,3),ssd:new T.Vector3(5,2,-1),cooler:new T.Vector3(-5,2,2),psu:new T.Vector3(5,.8,4),power:new T.Vector3(0,1,5)}[type];const g=part(type);g.position.copy(pos);scene.add(g);objects[type]=g;selectedPart=type;updateInfo(type);if($('#installBtn'))$('#installBtn').disabled=false;$$('.part-choice').forEach(b=>b.classList.toggle('selected',b.dataset.part===type));status(`تم إظهار ${names[type]} — اسحبها أو اضغط تركيب القطعة.`)}
function install(){if(!selectedPart||!objects[selectedPart])return;const t=selectedPart;objects[t].position.copy(targets[t]);installed.add(t);selectedPart=null;addXP(25);const n=installed.size,p=Math.round(n/7*100);text($('#buildCount'),n);text($('#buildPercent'),p+'%');if($('#progressBar'))$('#progressBar').style.width=p+'%';if($('#installBtn'))$('#installBtn').disabled=true;status(`✅ تم تركيب ${names[t]} — +25 XP`);if(n===7){if($('#readyBox'))$('#readyBox').innerHTML='🏆 <b>اكتمل التجميع!</b><br><small>كل القطع الأساسية مركبة.</small>';status('🏆 اكتمل تجميع الكمبيوتر!')}}
function resetBuild(){Object.values(objects).forEach(o=>scene.remove(o));Object.keys(objects).forEach(k=>delete objects[k]);installed.clear();selectedPart=null;if($('#installBtn'))$('#installBtn').disabled=true;text($('#buildCount'),0);text($('#buildPercent'),'0%');if($('#progressBar'))$('#progressBar').style.width='0%';status('تمت إعادة التجميع. المازربورد جاهزة.')}
function down(e){const r=renderer.domElement.getBoundingClientRect(),p=new T.Vector2((e.clientX-r.left)/r.width*2-1,-(e.clientY-r.top)/r.height*2+1),ray=new T.Raycaster();ray.setFromCamera(p,camera);const hits=ray.intersectObjects(Object.values(objects),true);if(hits.length){let o=hits[0].object;while(o.parent&&o.parent!==scene)o=o.parent;if(o.userData.partType){selectedPart=o.userData.partType;dragging=o;updateInfo(selectedPart);if($('#installBtn'))$('#installBtn').disabled=false;return}}viewDrag=true;lastX=e.clientX;lastY=e.clientY}
function move(e){if(dragging){dragging.position.x+=(e.clientX-lastX)*.018;dragging.position.z+=(e.clientY-lastY)*.018}else if(viewDrag){rotY+=(e.clientX-lastX)*.008;rotX+=(e.clientY-lastY)*.006;rotX=Math.max(-1.25,Math.min(.35,rotX));applyCamera()}lastX=e.clientX;lastY=e.clientY}
function up(){dragging=null;viewDrag=false}
function wheel(e){e.preventDefault();zoom=Math.max(6,Math.min(18,zoom+e.deltaY*.012));applyCamera()}
function init3D(TH){if(initialized)return;T=TH;mat={pcb:M(0x10211d,.65,.3),black:M(0x070a0f,.3,.75),dark:M(0x151c25,.4,.55),silver:M(0xb2bac3,.25,.8),white:M(0xe9eef3,.22,.65),cyan:M(0x16ddff,.25,.45),gold:M(0xd8ae45,.22,.85)};scene=new T.Scene();scene.background=new T.Color(0x050912);camera=new T.PerspectiveCamera(42,1,.1,100);renderer=new T.WebGLRenderer({antialias:true,powerPreference:'high-performance'});renderer.setPixelRatio(Math.min(devicePixelRatio||1,2));if(renderer.outputEncoding!==undefined)renderer.outputEncoding=T.sRGBEncoding;mount.innerHTML='';mount.appendChild(renderer.domElement);scene.add(new T.HemisphereLight(0xa7dcff,0x111722,2.2));const key=new T.DirectionalLight(0xffffff,3);key.position.set(6,12,8);scene.add(key);const p1=new T.PointLight(0x466fff,45,18);p1.position.set(-6,5,-5);scene.add(p1);const p2=new T.PointLight(0x00e5ff,30,15);p2.position.set(6,3,-3);scene.add(p2);const ground=new T.Mesh(new T.PlaneGeometry(30,30),new T.MeshStandardMaterial({color:0x050a11,roughness:.9}));ground.rotation.x=-Math.PI/2;ground.position.y=-.2;scene.add(ground);makeBoard();makeTargets();resize();applyCamera();renderer.domElement.addEventListener('pointerdown',down);renderer.domElement.addEventListener('pointermove',move);renderer.domElement.addEventListener('pointerup',up);renderer.domElement.addEventListener('pointerleave',up);renderer.domElement.addEventListener('wheel',wheel,{passive:false});window.addEventListener('resize',resize);initialized=true;status('جاهز — المازربورد 3D تعمل الآن. اسحب بالماوس للدوران.');const loop=()=>{if(autoRotate&&!viewDrag){rotY+=.003;applyCamera()}renderer.render(scene,camera);requestAnimationFrame(loop)};loop()}
$$('.part-choice').forEach(b=>b.addEventListener('click',()=>showPart(b.dataset.part)));$('#installBtn')?.addEventListener('click',install);$('#resetBuild')?.addEventListener('click',resetBuild);$('#rotateBtn')?.addEventListener('click',()=>{autoRotate=!autoRotate;$('#rotateBtn').classList.toggle('active',autoRotate)});$('#homeBtn')?.addEventListener('click',()=>{rotX=-.58;rotY=.55;zoom=11;applyCamera()});$('#wireBtn')?.addEventListener('click',()=>{wire=!wire;if(renderer)renderer.domElement.style.filter=wire?'contrast(1.1) brightness(1.15)':'none'});
status('⏳ جاري تشغيل مختبر 3D...');loadThree().then(init3D).catch(e=>{console.error(e);status('⚠️ تعذر تحميل محرك 3D. تحقق من اتصال الإنترنت.');if(mount)mount.innerHTML='<div style="display:grid;place-items:center;height:100%;min-height:420px;color:#8fa8bd;text-align:center;padding:30px"><div><div style="font-size:48px">🌐</div><b style="font-size:20px">تعذر تحميل محرك 3D</b><p>تم تجربة أكثر من مصدر. أعد تحميل الصفحة بعد التأكد من الإنترنت.</p></div></div>'});
})();